### ISSUE TITLE
Support Breast Cancer Semantic Segmentation (BCSS) dataset

### ISSUE THREAD

**Issue by ioangatop** [kaiko-ai/eva#427]
[The BCSS dataset](https://github.com/CancerDataScience/CrowdsourcingDataset-Amgadetal2019) contains over 20,000 segmentation annotations of tissue region from breast cancer images from TCGA. This large-scale dataset was annotated through the collaborative effort of pathologists, pathology residents, and medical students using the [Digital Slide Archive](https://digitalslidearchive.github.io/digital_slide_archive/).  It enables the generation of highly accurate machine-learning models for tissue segmentation.

More here: https://github.com/PathologyDataScience/BCSS

**Comment by nkaenzig** [comment]
Added in https://github.com/kaiko-ai/eva/pull/559
